### ISSUE TITLE
presto-service 起不来

### ISSUE THREAD

**Issue by 1074559124** [analysys/presto-hbase-connector#10]
2019-06-28T18:09:40.392+0800	INFO	main	Bootstrap	zookeeper-znode-parent                null     -- n/a --
2019-06-28T18:09:40.556+0800	ERROR	main	com.analysys.presto.connector.hbase.frame.HBaseConnectorFactory	Unable to create injector, see the following errors:

1) Error: Invalid configuration property zookeeper-znode-parent: may not be null (for class com.analysys.presto.connector.hbase.meta.HBaseConfig.zookeeperZnodeParent)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error: Invalid configuration property zookeeper-znode-parent: may not be null (for class com.analysys.presto.connector.hbase.meta.HBaseConfig.zookeeperZnodeParent)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:241)
	at com.analysys.presto.connector.hbase.frame.HBaseConnectorFactory.create(HBaseConnectorFactory.java:56)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:323)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:195)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:187)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:173)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:131)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:73)

2019-06-28T18:09:40.557+0800	ERROR	main	com.facebook.presto.server.PrestoServer	connector is null
java.lang.NullPointerException: connector is null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.facebook.presto.connector.ConnectorManager$MaterializedConnector.<init>(ConnectorManager.java:348)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:195)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:187)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:173)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:131)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:73)

2019-06-28T18:09:40.557+0800	INFO	Thread-94	io.airlift.bootstrap.LifeCycleManager	Life cycle st

**Comment by Crossoverrr** [comment]
catalogs/hbase.properties中缺少这一个参数：
zookeeper-znode-parent

**Comment by JasonLi-cn** [comment]
遇到个类似的问题：
`2020-10-08T20:14:49.860+0800	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog etc/catalog/hbase.properties --
2020-10-08T20:14:50.094+0800	ERROR	main	com.analysys.presto.connector.hbase.frame.HBaseConnectorFactory	java.lang.NullPointerException
javax.validation.ConstraintDefinitionException: java.lang.NullPointerException
	at org.apache.bval.jsr.ConstraintValidation.validateGroupContext(ConstraintValidation.java:166)
	at org.apache.bval.jsr.ConstraintValidation.validate(ConstraintValidation.java:144)
	at org.apache.bval.util.ValidationHelper.validateProperty(ValidationHelper.java:234)
	at org.apache.bval.jsr.ClassValidator.validateBean(ClassValidator.java:462)
	at org.apache.bval.jsr.ClassValidator.validateBeanNet(ClassValidator.java:409)
	at org.apache.bval.jsr.ClassValidator.validateBeanWithGroups(ClassValidator.java:154)
	at org.apache.bval.jsr.ClassValidator.validate(ClassValidator.java:142)
	at io.airlift.configuration.ConfigurationFactory.validate(ConfigurationFactory.java:413)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:386)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:317)
	at io.airlift.configuration.ConfigurationProvider.get(ConfigurationProvider.java:67)
	at io.airlift.configuration.ConfigurationFactory.validateRegisteredConfigurationProvider(ConfigurationFactory.java:230)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:202)
	at com.analysys.presto.connector.hbase.frame.HBaseConnectorFactory.create(HBaseConnectorFactory.java:56)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:341)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:210)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:202)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:188)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:131)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:73)
Caused by: java.lang.NullPointerException
	at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1413)
	at org.apache.commons.lang3.ClassUtils.isAssignable(ClassUtils.java:594)
	at org.apache.commons.lang3.reflect.TypeUtils.isAssignable(TypeUtils.java:376)
	at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:900)
	at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:798)
	at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:784)
	at org.apache.bval.jsr.ConstraintValidation.getValidatorsTypes(ConstraintValidation.java:381)
	at org.apache.bval.jsr.ConstraintValidation.getConstraintValidator(ConstraintValidation.java:249)
	at org.apache.bval.jsr.ConstraintValidation.validateGroupContext(ConstraintValidation.java:157)
	... 21 more


2020-10-08T20:14:50.095+0800	ERROR	main	com.facebook.presto.server.PrestoServer	connector is null
java.lang.NullPointerException: connector is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at com.facebook.presto.connector.ConnectorManager$MaterializedConnector.<init>(ConnectorManager.java:366)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:210)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:202)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:188)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:131)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:73)`

帮忙看一下

**Comment by Crossoverrr** [comment]
> 遇到个类似的问题：
> `2020-10-08T20:14:49.860+0800 INFO main com.facebook.presto.metadata.StaticCatalogStore -- Loading catalog etc/catalog/hbase.properties --
> 2020-10-08T20:14:50.094+0800 ERROR main com.analysys.presto.connector.hbase.frame.HBaseConnectorFactory java.lang.NullPointerException
> javax.validation.ConstraintDefinitionException: java.lang.NullPointerException
> at org.apache.bval.jsr.ConstraintValidation.validateGroupContext(ConstraintValidation.java:166)
> at org.apache.bval.jsr.ConstraintValidation.validate(ConstraintValidation.java:144)
> at org.apache.bval.util.ValidationHelper.validateProperty(ValidationHelper.java:234)
> at org.apache.bval.jsr.ClassValidator.validateBean(ClassValidator.java:462)
> at org.apache.bval.jsr.ClassValidator.validateBeanNet(ClassValidator.java:409)
> at org.apache.bval.jsr.ClassValidator.validateBeanWithGroups(ClassValidator.java:154)
> at org.apache.bval.jsr.ClassValidator.validate(ClassValidator.java:142)
> at io.airlift.configuration.ConfigurationFactory.validate(ConfigurationFactory.java:413)
> at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:386)
> at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:317)
> at io.airlift.configuration.ConfigurationProvider.get(ConfigurationProvider.java:67)
> at io.airlift.configuration.ConfigurationFactory.validateRegisteredConfigurationProvider(ConfigurationFactory.java:230)
> at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:202)
> at com.analysys.presto.connector.hbase.frame.HBaseConnectorFactory.create(HBaseConnectorFactory.java:56)
> at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:341)
> at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:210)
> at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:202)
> at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:188)
> at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
> at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
> at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:131)
> at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:73)
> Caused by: java.lang.NullPointerException
> at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1413)
> at org.apache.commons.lang3.ClassUtils.isAssignable(ClassUtils.java:594)
> at org.apache.commons.lang3.reflect.TypeUtils.isAssignable(TypeUtils.java:376)
> at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:900)
> at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:798)
> at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:784)
> at org.apache.bval.jsr.ConstraintValidation.getValidatorsTypes(ConstraintValidation.java:381)
> at org.apache.bval.jsr.ConstraintValidation.getConstraintValidator(ConstraintValidation.java:249)
> at org.apache.bval.jsr.ConstraintValidation.validateGroupContext(ConstraintValidation.java:157)
> ... 21 more
> 
> 2020-10-08T20:14:50.095+0800 ERROR main com.facebook.presto.server.PrestoServer connector is null
> java.lang.NullPointerException: connector is null
> at java.base/java.util.Objects.requireNonNull(Objects.java:246)
> at com.facebook.presto.connector.ConnectorManager$MaterializedConnector.(ConnectorManager.java:366)
> at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:210)
> at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:202)
> at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:188)
> at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
> at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
> at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:131)
> at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:73)`
> 
> 帮忙看一下

你好，方便提供一下你用的tag或者分支名称吗？

**Comment by JasonLi-cn** [comment]
你好，这个问题是出现在presto-db中，我现在换成了presto-sql但是又有别的问题。
presto：presto-server-338.tar.gz
connector: master
/home/xxx/presto-sql/presto-server/hbase/default/statlogupload_index_string.json
`{
    "tableName":"statlogupload_index_string",
    "schemaName":"default",
    "rowKeyFormat":"rowkey",
    "describe":"Table for test!",
    "rowKeySeparator":"",
    "rowKeyFirstCharRange":"a~z,0~9",
    "columns":[
        {
            "family":"",
            "columnName":"rowkey",
            "comment":"The RowKey column of table!",
            "type":"varchar",
            "isRowKey":true
        },
        {
            "family":"v",
            "columnName":"test",
            "comment":"Column for test!",
            "type":"varchar",
            "isRowKey":false
        }
    ]
}`

/home/xxx/presto-sql/presto-server/etc/catalog/hbase.properties
`connector.name=hbase
zookeeper-quorum=pd01.net,pd02.net,pd03.net
zookeeper-client-port=2181
zookeeper-znode-parent=/hbase-pd
hbase-cluster-distributed=true
presto-server-port=8285
random-schedule-redundant-split=false
meta-dir=/home/xxx/presto-sql/presto-server/hbase`

` presto:default> show schemas;
       Schema       
--------------------
 information_schema 
(1 row)

Query 20201009_020904_00002_y6x6x, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.23 [1 rows, 23B] [4 rows/s, 101B/s]`

**Comment by Crossoverrr** [comment]
可以去8285页面或者server.log看看报错的日志。
试试看把zookeeper-quorum的值改成pd01.net,pd02.net,pd03.net:2181还报错吗。

**Comment by Crossoverrr** [comment]
show tables正常吗？

**Comment by JasonLi-cn** [comment]
你好，server.log里并没有报错，并且，我把catalog/hbase.properties中的meta-dir注释掉，也不会报错。zk那个配置改了也不行

**Comment by Crossoverrr** [comment]
8285上的sql日志有报错吗？

**Comment by Crossoverrr** [comment]
> meta-dir

show schema操作是直接调用hbase的`Admin#listNamespaceDescriptors`方法来获取数据，还没有用到meta-dir这个参数。desc table获取表的元数据时会用到他。
问下你用的是哪个版本的代码？

**Comment by JasonLi-cn** [comment]
> 8285上的sql日志有报错吗？
没报错信息，我用的master分支

**Comment by Crossoverrr** [comment]
> > 8285上的sql日志有报错吗？
> > 没报错信息，我用的master分支

master分支还处在测试阶段，他是基于hbase 2.0实现的。如果不是hbase 2.0，建议用release的版本meta-0.1.5。

**Comment by JasonLi-cn** [comment]
> > > 8285上的sql日志有报错吗？
> > > 没报错信息，我用的master分支
> 
> master分支还处在测试阶段，他是基于hbase 2.0实现的。如果不是hbase 2.0，建议用release的版本meta-0.1.5。

HBase版本是hbase-2.2.1.9
我换成其它分支试试吧

**Comment by JasonLi-cn** [comment]
branch：dev_0.1.5
`2020-10-09T22:20:32.525+0800	ERROR	main	com.analysys.presto.connector.hbase.frame.HBaseConnectorFactory	java.lang.NullPointerException
javax.validation.ConstraintDefinitionException: java.lang.NullPointerException
	at org.apache.bval.jsr.ConstraintValidation.validateGroupContext(ConstraintValidation.java:166)
	at org.apache.bval.jsr.ConstraintValidation.validate(ConstraintValidation.java:144)
	at org.apache.bval.util.ValidationHelper.validateProperty(ValidationHelper.java:234)
	at org.apache.bval.jsr.ClassValidator.validateBean(ClassValidator.java:462)
	at org.apache.bval.jsr.ClassValidator.validateBeanNet(ClassValidator.java:409)
	at org.apache.bval.jsr.ClassValidator.validateBeanWithGroups(ClassValidator.java:154)
	at org.apache.bval.jsr.ClassValidator.validate(ClassValidator.java:142)
	at io.airlift.configuration.ConfigurationFactory.validate(ConfigurationFactory.java:413)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:386)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:317)
	at io.airlift.configuration.ConfigurationProvider.get(ConfigurationProvider.java:67)
	at io.airlift.configuration.ConfigurationFactory.validateRegisteredConfigurationProvider(ConfigurationFactory.java:230)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:202)
	at com.analysys.presto.connector.hbase.frame.HBaseConnectorFactory.create(HBaseConnectorFactory.java:61)
	at io.prestosql.connector.ConnectorManager.createConnector(ConnectorManager.java:349)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:208)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:200)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:186)
	at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.prestosql.server.Server.doStart(Server.java:117)
	at io.prestosql.server.Server.lambda$start$0(Server.java:72)
	at io.prestosql.$gen.Presto_338____20201009_142023_1.run(Unknown Source)
	at io.prestosql.server.Server.start(Server.java:72)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:38)
Caused by: java.lang.NullPointerException
	at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1413)
	at org.apache.commons.lang3.ClassUtils.isAssignable(ClassUtils.java:594)
	at org.apache.commons.lang3.reflect.TypeUtils.isAssignable(TypeUtils.java:376)
	at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:900)
	at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:798)
	at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:784)
	at org.apache.bval.jsr.ConstraintValidation.getValidatorsTypes(ConstraintValidation.java:381)
	at org.apache.bval.jsr.ConstraintValidation.getConstraintValidator(ConstraintValidation.java:249)
	at org.apache.bval.jsr.ConstraintValidation.validateGroupContext(ConstraintValidation.java:157)
	... 24 more`

**Comment by Crossoverrr** [comment]
dev_0.1.5是基于hbase 1.0实现的，需要手动迁移到2.0版本

**Comment by Crossoverrr** [comment]
看日志可能是jdk版本的问题

**Comment by JasonLi-cn** [comment]
> 看日志可能是jdk版本的问题

应该是，估计是lang3的兼容问题
