### ISSUE TITLE
配置hbase.propertites 之后报错

### ISSUE THREAD

**Issue by GoodJeek** [analysys/presto-hbase-connector#22]
2020-01-02T20:42:09.519+0800	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector hbase
java.lang.IllegalArgumentException: No factory for connector hbase
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:194)
	at com.
这是什么原因导致的？尝试了多次仍然不行

**Comment by Crossoverrr** [comment]
方便发下你用的presto版本和presto-hbase-connector的tag号吗。
最新版本的组件已经迁移到了prestosql-315版本了，看报错日志里还是prestodb的类路径。

**Comment by Crossoverrr** [comment]
暂时先关闭这个issue，如果还有问题可以再次打开  :)
