### ISSUE TITLE
能否支持presto-332

### ISSUE THREAD

**Issue by louyz** [analysys/presto-hbase-connector#31]
能否支持一下presto-332

**Comment by Crossoverrr** [comment]
你好！当前的版本支持prestosql-315版本，如果在332版本上运行有什么问题请及时与我联系！

**Comment by louyz** [comment]
在 332 版本中如果不修改依赖 <presto.version>332</presto.version> presto不能正常启动，修改后使用jar启动  报错信息如下
2020-05-27T19:13:32.345+0800	ERROR	remote-task-callback-13	io.prestosql.execution.StageStateMachine	Stage 20200527_111331_00001_n4vqc.2 failed
java.lang.NullPointerException
	at com.analysys.presto.connector.hbase.meta.HBaseTables.getSchemaNames(HBaseTables.java:83)
	at com.analysys.presto.connector.hbase.meta.HBaseMetadata.listSchemaNames(HBaseMetadata.java:102)
	at com.analysys.presto.connector.hbase.meta.HBaseMetadata.listSchemaNames(HBaseMetadata.java:63)
	at io.prestosql.metadata.MetadataManager.listSchemaNames(MetadataManager.java:292)
	at io.prestosql.metadata.MetadataListing.listSchemas(MetadataListing.java:59)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.addSchemataRecords(InformationSchemaPageSource.java:305)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:219)
	at io.prestosql.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:176)
	at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:302)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_332____20200527_110752_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Crossoverrr** [comment]
这个问题有可能是获取admin有问题了，能验证一下吗？
![image](https://user-images.githubusercontent.com/33892550/83089652-6dd88b00-a0c9-11ea-9fca-4412303bd277.png)

**Comment by louyz** [comment]
你好，已经验证打印日志，获取的admin为空，

**Comment by Crossoverrr** [comment]
可以测试一下这个hbase的环境能正常访问吗？

**Comment by louyz** [comment]
Hbase可以正常访问

**Comment by Crossoverrr** [comment]
用代码的方式能访问吗？

**Comment by louyz** [comment]
用代码是创建一个springboot 的项目，直接链接服务器上的hbase吗？

**Comment by toriycn** [comment]
我添加了一个338支持的版本。你可以试试看。
