### ISSUE TITLE
hbase的表名有大写字母的会出现表不存在的异常

### ISSUE THREAD

**Issue by hanrongsu** [analysys/presto-hbase-connector#34]
你好！
当表名有大写字母的会出现以下的异常，实际表名为ApiMetaData。在获取表名时是不是都统一转换成小写了？ 
2020-07-03T10:35:39.795+0800    ERROR   Query-20200703_023539_00006_7pa7n-534   com.analysys.presto.connector.hbase.connection.HBaseClientManager       apimetadata
org.apache.hadoop.hbase.TableNotFoundException: apimetadata
        at org.apache.hadoop.hbase.client.HBaseAdmin.getTableDescriptor(HBaseAdmin.java:458)
        at com.analysys.presto.connector.hbase.connection.HBaseClientManager.getTable(HBaseClientManager.java:108)
        at com.analysys.presto.connector.hbase.meta.HBaseMetadata.getTableMetadata(HBaseMetadata.java:96)
        at com.analysys.presto.connector.hbase.meta.HBaseMetadata.getTableMetadata(HBaseMetadata.java:89)
        at io.prestosql.metadata.MetadataManager.getTableMetadata(MetadataManager.java:450)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:933)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:272)
        at io.prestosql.sql.tree.Table.accept(Table.java:53)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:286)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1879)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1040)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:272)
        at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:286)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:296)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:742)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:272)
        at io.prestosql.sql.tree.Query.accept(Query.java:107)
        at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:286)
        at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:264)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:76)
        at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:68)
        at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:184)
        at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:92)
        at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:706)
        at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:118)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by toriycn** [comment]
是的，目前传输过程中，所有获取到的表名全部都是小写的。所以，目前只是支持小写表名的，后面我会在后期版本中添加大写的支持的。

**Comment by hoey94** [comment]
支支持小写也太局限了。。

**Comment by louyz** [comment]
支持mysql表名大写预计啥时候更新，请大佬支持

**Comment by louyz** [comment]
大佬，hbase表名大写支持预计啥时候更新啊，请大佬支持

**Comment by dingqiang0371** [comment]
表名和字段名大写都不行，希望能尽快添加大写的支持的。谢谢

**Comment by Crossoverrr** [comment]
这个是因为presto会在内部把表名和字段名统一转换为小写，所以连接器这里需要额外做配置才能实现这个功能。
