### ISSUE TITLE
presto 接入Hbase出现的问题

### ISSUE THREAD

**Issue by gitHub-dl** [analysys/presto-hbase-connector#42]
![企业微信截图_15972283783170](https://user-images.githubusercontent.com/45382890/90005811-55d8d680-dcca-11ea-8042-8ebea03ec0b7.png) 是不是配置文件不对还是怎么的, 源码是没有动过的

**Comment by gitHub-dl** [comment]
2020-08-12T18:16:22.879+0800	ERROR	20200812_101622_00002_v53be.2.0-0-112	com.analysys.presto.connector.hbase.meta.HBaseTables	org.apache.hadoop.hbase.NamespaceNotFoundException: information_schema
	at org.apache.hadoop.hbase.master.ClusterSchemaServiceImpl.getNamespace(ClusterSchemaServiceImpl.java:119)
	at org.apache.hadoop.hbase.master.HMaster.getTableDescriptors(HMaster.java:3426)
	at org.apache.hadoop.hbase.master.HMaster.listTableDescriptors(HMaster.java:3383)
	at org.apache.hadoop.hbase.master.HMaster.listTableDescriptorsByNamespace(HMaster.java:3315)
	at org.apache.hadoop.hbase.master.MasterRpcServices.listTableDescriptorsByNamespace(MasterRpcServices.java:1275)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:413)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:324)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:304)

org.apache.hadoop.hbase.NamespaceNotFoundException: org.apache.hadoop.hbase.NamespaceNotFoundException: information_schema
	at org.apache.hadoop.hbase.master.ClusterSchemaServiceImpl.getNamespace(ClusterSchemaServiceImpl.java:119)
	at org.apache.hadoop.hbase.master.HMaster.getTableDescriptors(HMaster.java:3426)
	at org.apache.hadoop.hbase.master.HMaster.listTableDescriptors(HMaster.java:3383)
	at org.apache.hadoop.hbase.master.HMaster.listTableDescriptorsByNamespace(HMaster.java:3315)
	at org.apache.hadoop.hbase.master.MasterRpcServices.listTableDescriptorsByNamespace(MasterRpcServices.java:1275)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:413)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:324)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:304)

这是报错信息!!!

**Comment by Crossoverrr** [comment]
你好！查询sql能贴一下吗？表的namespace是什么也发一下吧。   :)

**Comment by tushengxia** [comment]
> 你好！查询sql能贴一下吗？表的namespace是什么也发一下吧。 :)

我也遇到了这个问题，启动presto服务的时候 就报了这个错误，虽然不影响运行。
