### ISSUE TITLE
Trino support

### ISSUE THREAD

**Issue by jerryleooo** [analysys/presto-hbase-connector#55]
Seems the connector doesn't work with Trino 356:

```
2022-01-07T17:34:04.826+0800	INFO	main	io.trino.server.PluginManager	-- Loading plugin /home/work/apps/tools/presto-server/trino-server-356/plugin/hbase --
2022-01-07T17:34:04.870+0800	ERROR	main	io.trino.server.Server	No service providers of type io.trino.spi.Plugin
java.lang.IllegalStateException: No service providers of type io.trino.spi.Plugin
	at com.google.common.base.Preconditions.checkState(Preconditions.java:591)
	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:139)
	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:129)
	at io.trino.server.ServerPluginsProvider.loadPlugins(ServerPluginsProvider.java:48)
	at io.trino.server.PluginManager.loadPlugins(PluginManager.java:110)
	at io.trino.server.Server.doStart(Server.java:121)
	at io.trino.server.Server.lambda$start$0(Server.java:77)
	at io.trino.$gen.Trino_356____20220107_093347_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:77)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)


2022-01-07T17:34:04.873+0800	INFO	Thread-88	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
```

**Comment by Crossoverrr** [comment]
We don't have the plan to migrate this connector to Trino, we are glad if someone can do some contribution :)

**Comment by jerryleooo** [comment]
Thanks, I create https://github.com/jerryleooo/trino-hbase-connector based on this, closing
